version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/astrojs_ecommerce
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6InRlY2hAcGxlbmkuYXBwIiwiZXhwIjoxNzI1NzgzNDE1LCJpYXQiOjE3MjU3ODM0MTV9.lnTAyaphF_ssG2miTssEmHv-m39NTUU53Dptp8N-Rmg
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: